# Generated by Django 5.1.1 on 2024-10-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="Введите название", max_length=150, verbose_name="Заголовок"
            ),
        ),
    ]
