# Generated by Django 5.1.1 on 2024-11-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_owner_product_publish_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["title"],
                "permissions": [("can_unpublish_product", "can unpublish product")],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
